# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'instruct.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ins(object):
    def setupUi(self, ins):
        ins.setObjectName("ins")
        ins.resize(732, 488)
        ins.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.centralwidget = QtWidgets.QWidget(ins)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.horizontalLayout.addLayout(self.verticalLayout)
        ins.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ins)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 732, 26))
        self.menubar.setObjectName("menubar")
        ins.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ins)
        self.statusbar.setObjectName("statusbar")
        ins.setStatusBar(self.statusbar)

        self.retranslateUi(ins)
        QtCore.QMetaObject.connectSlotsByName(ins)

    def retranslateUi(self, ins):
        _translate = QtCore.QCoreApplication.translate
        ins.setWindowTitle(_translate("ins", "MainWindow"))
        self.label.setText(_translate("ins", "It is a game in which a player can test his typing speed"))
        self.label_6.setText(_translate("ins", "Player has to type a word which is shown in the box and on pressing enter key new word will be displayed"))
        self.label_3.setText(_translate("ins", "If entered word is correct player will be rewarded with 1 point,otherwise 0 point."))
        self.label_5.setText(_translate("ins", "Player will be given 60 seconds to complete the task,the number of words entered by him will be final score."))
        self.label_7.setText(_translate("ins", "Game can be played in three modes:Easy,Medium and Difficult."))
        self.label_8.setText(_translate("ins", "Game can be reseted on clicking reset button"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ins = QtWidgets.QMainWindow()
    ui = Ui_ins()
    ui.setupUi(ins)
    ins.show()
    sys.exit(app.exec_())
